#!/bin/bash
echo "Welcome to Table Menu :)"
PS3='Enter your choice: '
options=("Create Table" "List Table" "Drop Table" "Insert into Table" "Select from Table" "Delete from Table" "Update Table" "Exit")
select op in "${options[@]}"
do
    case $op in
        "Create Table")
            bash ./createtable.sh

            ;;
        "List Table")
            bash ./listtable.sh

            ;;
        "Drop Table")
            bash ./DropTable.sh

            ;;
        "Insert into Table")
            bash ./insertTable.sh

            ;;
	    "Select from Table")
	        bash ./selectTable.sh

	    ;;
        "Delete from Table")
	        bash ./DeleteTable.sh

	    ;;
	    "Update Table")
            bash ./UpdateTable.sh

	    ;;
        "Exit")
            break

            ;;
        *) echo "unavailable option $REPLY";;
    esac
done
