#!/usr/bin/bash 
#PK Exist or not 

export LC_COLLATE=C
shopt -s extglob

#Call tables methods 
. ../Methods/Table-methods.sh


#Input
read -p "enter table name you want insert into " tableName

Table_Check

metadata="$tableName-metadata"

declare -i NF=0
# get the second field after PK --which mean rhe metadate of PK 
pk=$(awk 'BEGIN{FS=":"}
{
i=1
while(i<=NF){
if ($i=="pk"){
print $((i+1))}
i++
}
}
' ../Databases/$mydb/$metadata) # will passed from teble menu


insertspecefic(){



declare -i i=1
echo  "" >> ./databases/$mydb/$tableName

# Insert the PK seperatly 
read -p "Your new PK: " primary
PK_exist



while (true)
do
    if ((  $i != 5-1 ));then #loop on table
    
    s=$(sed -n /name/p databases/$mydb/$tableName | awk -F: -v i=$i '{print $i}')
    echo -n "please enter $s = "
    read -p "" input
    
    echo -n $input":" >> ./databases/$mydb/$tableName
    i=$i+1
        
    fi
    break
done
}
